### ISSUE TITLE
Allow customizing of the work folder

### ISSUE THREAD

**Issue by bburgin** [Cisco-Talos/Mussels#18]
Customizing the work folder could be useful for running multiple Mussels instances in parallel.
Since for the parallel case, I think the work folder would need to be unique.
Users may be able to get by with the same install folder. I am unclear if Mussels would do the
right thing there. If anything, the user could specify separate install folders for this case.

**Comment by micahsnyder** [comment]
@bburgin Does the change described in febf021 sound good?

Using the arguments `msl build zlib -w ./work` should result in a work directory at ./work, with build artifacts under ./work/<target>

**Comment by bburgin** [comment]
Looks good. I guess it begs the question: What if the user wants to also customize the downloads dir or logs dir?

**Comment by micahsnyder** [comment]
Heh it does indeed beg that question.  It should be easy enough to add, so I'll go ahead and add it to the PR.

**Comment by micahsnyder** [comment]
Updated the PR with commit e8af6c5. Thoughts?

**Comment by bburgin** [comment]
Looks good.
